# Generated by Django 4.2.1 on 2023-06-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_tag_blog_category_blog_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='blog'),
        ),
        migrations.AlterField(
            model_name='subblog',
            name='image',
            field=models.ImageField(upload_to='blog'),
        ),
    ]
