# Generated by Django 4.2.1 on 2023-06-07 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subblog',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_blog', to='blog.blog'),
        ),
    ]
