# Generated by Django 4.2.1 on 2023-06-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blog_slug_alter_subblog_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='views',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
